import type { Product } from './catalog';

const W=(id:string,brand:string,name:string,description:string,price:number|null,boxQty:number|null=null,boxPrice:number|null=null):Product=>({id,brand,name,category:'Whisky',description,price,boxQty,boxPrice,stock:null,emoji:'🥃'});

export const whiskyProducts:Product[]=[
W('wh-black-white-075','Black & White','Black & White 0,75 L',"Blended de 8 años de la Casa Buchanan’s. Es ligero, fresco y picante con un toque de humo. Posee un delicioso sabor a notas cítricas, miel y un toque de roble.",15.70,12,180),
W('wh-black-white-1l','Black & White','Black & White 1 L',"Blended de 8 años de la Casa Buchanan’s. Es ligero, fresco y picante con un toque de humo. Posee un delicioso sabor a notas cítricas, miel y un toque de roble.",18.70,12,215),
W('wh-dewars-white-075','Dewar’s','Dewar’s White Label 0,75 L','Resultado de la mezcla de hasta 40 whiskies de single malt y de grano en cada botella, tiene un añejamiento mínimo de 5 años.',16.50,12,186),
W('wh-dewars-white-1l','Dewar’s','Dewar’s White Label 1 L','Resultado de la mezcla de hasta 40 whiskies de single malt y de grano en cada botella, tiene un añejamiento mínimo de 5 años.',20.50,12,233),
W('wh-william-lawsons-075','William Lawson’s','William Lawson’s 0,75 L','Mezcla de whiskies de malta y grano, se añeja en barricas de roble, que anteriormente contuvieron jerez, durante un mínimo de 2 años.',null,12,null),
W('wh-william-lawsons-1l','William Lawson’s','William Lawson’s 1 L','Mezcla de whiskies de malta y grano, se añeja en barricas de roble, que anteriormente contuvieron jerez, durante un mínimo de 2 años.',17.95,12,205),
W('wh-clan-macgregor-075','Clan MacGregor','Clan MacGregor 0,75 L','Whisky pioneer blend. Hecho a mano desde las cuatro esquinas de Escocia, cruje con especias y está lleno de sabores vibrantes y ahumados.',13.75,12,156),
W('wh-clan-macgregor-1l','Clan MacGregor','Clan MacGregor 1 L','Whisky pioneer blend. Hecho a mano desde las cuatro esquinas de Escocia, cruje con especias y está lleno de sabores vibrantes y ahumados.',18.90,12,216),
W('wh-grants-triple-075','Grant’s','Grant’s Triple Wood 0,75 L','Añejado en tres tipos de barricas distintas que le ofrece un sabor delicioso y sedoso. De brillante color ámbar, en boca se percibe un equilibrio.',17.50,12,200),
W('wh-grants-triple-1l','Grant’s','Grant’s Triple Wood 1 L','Añejado en tres tipos de barricas distintas que le ofrece un sabor delicioso y sedoso. De brillante color ámbar, en boca se percibe un equilibrio.',19,12,215),
W('wh-cattos-075','Catto’s','Catto’s 0,75 L','Whisky tipo blended, en base a whisky de malta con pequeños aportes de otros granos cuidadosamente seleccionados. Sabor meloso y suave.',null,12,null),
W('wh-cattos-1l','Catto’s','Catto’s 1 L','Whisky tipo blended, en base a whisky de malta con pequeños aportes de otros granos cuidadosamente seleccionados. Sabor meloso y suave.',22.90,12,263),
W('wh-highland-cup-075','Highland Cup','Highland Cup 0,75 L','Mezcla de maltas y whiskies de grano ofrece un sabor suave, cálido y ligeramente sedoso.',15.95,12,180),
W('wh-highland-cup-1l','Highland Cup','Highland Cup 1 L','Mezcla de maltas y whiskies de grano ofrece un sabor suave, cálido y ligeramente sedoso.',18.95,12,216),
W('wh-hankey-075','Hankey Bannister','Hankey Bannister 0,75 L','Es una mezcla ligera, dulce y sutil con notas de miel y especias.',12.25,12,127),
W('wh-something-075','Something Special','Something Special 0,75 L','Creado en 1793 por la destilería William Hill. Mezcla de los mejores whiskies de malta y grano de Speyside para crear la inconfundible dulzura humeante.',null,12,null),
W('wh-something-1l','Something Special','Something Special 1 L','Creado en 1793 por la destilería William Hill. Mezcla de los mejores whiskies de malta y grano de Speyside para crear la inconfundible dulzura humeante.',23.50,12,265),
W('wh-chequers-1l','Chequers','Chequers 1 L','Es una mezcla de whisky escocés cuyos orígenes se remontan a muchos años. Sucesivas generaciones han guardado el secreto de Chequers.',null,12,null),
W('wh-cutty-sark-075','Cutty Sark','Cutty Sark 0,75 L','La mezcla de malta descansa más tiempo para suavizarla y se filtra a una temperatura más alta para darle más riqueza. Cada barril tiene la más alta calidad.',15,12,168),
W('wh-famous-grouse-075','The Famous Grouse','The Famous Grouse 0,75 L','La mezcla de malta descansa más tiempo para suavizarla y se filtra a una temperatura más alta para darle más riqueza.',19.35,12,220),
W('wh-famous-grouse-1l','The Famous Grouse','The Famous Grouse 1 L','La mezcla de malta descansa más tiempo para suavizarla y se filtra a una temperatura más alta para darle más riqueza.',21.50,12,240),
W('wh-ballantines-075','Ballantine’s','Ballantine’s 0,75 L','Whisky escocés mezclado fabricado por Pernod Ricard en Dumbarton, Escocia. El porcentaje de contenido de alcohol es del 40%.',25.50,12,294),
W('wh-jw-red-075','Johnnie Walker','Etiqueta Roja 0,75 L','Whisky pioneer blend. Hecho a mano desde las cuatro esquinas de Escocia, cruje con especias y está lleno de sabores vibrantes y ahumados, seguido de un suave lecho de vainilla.',17,12,192),
W('wh-jw-red-1l','Johnnie Walker','Etiqueta Roja 1 L','Whisky pioneer blend. Hecho a mano desde las cuatro esquinas de Escocia, cruje con especias y está lleno de sabores vibrantes y ahumados, seguido de un suave lecho de vainilla.',27.95,12,324),

W('wh-chivas-12-075','Chivas Regal','Chivas Regal 12 Años 0,75 L','Mezcla de los mejores whiskies de malta y grano madurados durante al menos 12 años, que brindan lujosas notas de miel y vainilla.',39.90,12,460),
W('wh-old-parr-12-075','Old Parr','Old Parr 12 Años 0,75 L','Destilado de granos finos, madurado durante 12 años para garantizar un carácter profundo y un sabor audaz y accesible para el paladar.',32.95,12,376),
W('wh-hankey-12-075','Hankey Bannister','Hankey Bannister 12 Años 0,75 L','Con un mínimo de 12 años de maduración en barricas de roble americano que antes habían albergado bourbons.',25,12,296),
W('wh-jw-black-sherry-075','Johnnie Walker','Etiqueta Negra Sherry Finish 0,75 L','Ofrece sabores similares de Etiqueta Negra con la dulzura añadida de higos y ciruelas que se derivan de su paso en barrica de jerez. Envejecido durante 12 años.',38.50,6,216),
W('wh-jw-black-075','Johnnie Walker','Etiqueta Negra 0,75 L','Creado usando sólo whiskies con un mínimo de 12 años de añejamiento de los 4 rincones de Escocia. Tiene un inconfundible carácter profundo, suave y complejo.',36.90,12,415),
W('wh-buchanans-12-075','Buchanan’s','Buchanan’s 12 Años 0,75 L','De los whiskies más icónicos y premiados del mundo. Tiene un perfil suave y fresco, su sabor es afrutado con notas cítricas combinadas con chocolate y miel.',38.50,12,444),
W('wh-cattos-12-075','Catto’s','Catto’s 12 Años 0,75 L','Whiskies de malta o de grano de las Highlands, Speyside y Lowlands de Escocia, envejecidos en barricas de roble.',25,12,288),
W('wh-dewars-12-075','Dewar’s','Dewar’s 12 Años 0,75 L','Elaborado a partir de los más finos whiskies de malta y grano, famoso por su mezcla de doble añejamiento, con 6 meses en casamiento en barricas de roble después de la maduración inicial.',32.90,6,378),
W('wh-grants-12-075','Grant’s','Grant’s 12 Años 0,75 L','Doce años es el tiempo en el que tardan los ricos y dulces sabores en entrar en acción. Luego pasa otros tres meses en barricas de Bourbon.',28.90,6,166),
W('wh-grants-12-1l','Grant’s','Grant’s 12 Años 1 L','Doce años es el tiempo en el que tardan los ricos y dulces sabores en entrar en acción. Luego pasa otros tres meses en barricas de Bourbon.',38.50,6,224),
W('wh-highland-cup-12-075','Highland Cup','Highland Cup 12 Años 0,75 L','Este escocés maduro de lujo es una mezcla impresionante de algunos de los whiskies de malta y grano, envejecidos en roble.',37.50,6,435),
W('wh-ballantines-12-075','Ballantine’s','Ballantine’s 12 Años 0,75 L','Un whisky dulce como la miel, perfectamente equilibrado con notas de roble y vainilla.',36.50,12,420),
W('wh-glenfiddich-12-075','Glenfiddich','Glenfiddich 12 Años 0,75 L','Whisky escocés de una sola malta con distintivos sabores a pera fresca, cremoso y con sabor a roble tostado con un acabado maduro, largo y suave.',66.50,12,780),
W('wh-balvenie-doublewood-075','The Balvenie','The Balvenie Double Wood 0,75 L','Whisky de malta escocés que adquiere su carácter distintivo gracias a su proceso de maduración en 2 tipos de madera. Pasa 12 años en barricas tradicionales de whisky y roble bourbon americano.',78.95,null,null),
W('wh-macallan-12-double-070','Macallan','Macallan 12 Años Double Cask 0,70 L','Engloba el estilo clásico Macallan y la dulzura inigualable del roble americano. Single malt equilibrado, con sabores a miel, cítrico y jengibre.',265.50,null,null),
W('wh-macallan-12-sherry-070','Macallan','Macallan 12 Años Sherry Oak Cask 0,70 L','Compuesta por whiskies single malt madurados exclusivamente en barricas de roble cuidadosamente escogidas que previamente han albergado jerez.',252.85,null,null),
W('wh-macallan-12-triple-070','Macallan','Macallan Triple Cask 12 Años 0,70 L','Single malt elaborado en una combinación de tres barricas: roble americano y europeo que previamente han albergado jerez y barricas de roble americano que antes contenían bourbon.',175.50,null,null),
W('wh-chivas-extra-13-075','Chivas Regal','Chivas Regal Extra 13 Años 0,75 L','El envejecimiento del Chivas clásico durante 13 años en barricas de Jerez Oloroso resulta en una experiencia de sabor incomparable y maravillosamente rica.',43.50,null,null),

W('wh-chivas-15-075','Chivas Regal','Chivas Regal 15 Años 0,75 L','Acabado en barricas de coñac para un whisky escocés mezclado verdaderamente lujoso; sabores refinados, afrutados y aterciopelados.',52.50,12,300),
W('wh-dimple-15-1l','Dimple','Dimple 15 Años 1 L','Whisky escocés de mezcla compuesto por más de 30 whiskies de malta y grano, fabricado por Haig.',149.90,12,1776),
W('wh-dewars-15-075','Dewar’s','Dewar’s 15 Años 0,75 L','Whisky escocés dulce y ligero. Gracias al exclusivo proceso de doble envejecimiento, es inusualmente suave con notas a miel.',78.90,6,462),
W('wh-jw-swing-075','Johnnie Walker','Swing 0,75 L','Whisky de 15 años creado inspirándose en los viajes marinos transatlánticos por Sir Alexander Walker, en 1932. Mezcla de 35 whiskies de malta y grano.',152.50,12,1800),
W('wh-jw-green-1l','Johnnie Walker','Green Label 1 L','Mezclado exclusivamente con Single Malts. Añejado durante al menos 15 años, reúne maltas de los cuatro rincones de Escocia.',null,12,null),
W('wh-jw-island-green-1l','Johnnie Walker','Island Green 1 L','Interpretación dinámica de Etiqueta Verde. Elaborado a partir de maltas Speyside, Highland, Lowland e Island maduradas durante al menos 15 años.',null,12,null),
W('wh-glenfiddich-15-075','Glenfiddich','Glenfiddich 15 Años 0,75 L','Whisky escocés de una sola malta, añejado en roble americano nuevo, roble americano y roble europeo.',89.90,null,null),
W('wh-buchanans-select-15-075','Buchanan’s','Buchanan’s Select 15 Años 0,75 L','Mezcla de los más finos single malts, madurada durante 15 años, con perfil audaz y complejo y notas de roble tostado.',121.50,null,null),
W('wh-macallan-double-15-070','Macallan','Macallan Double Cask 15 Años 0,70 L','Whisky de malta único equilibrado creado al traer la armonía perfecta de dos robles. El roble americano sazonado con jerez añade vainilla a la especia del roble europeo.',485.50,null,null),

W('wh-buchanans-18-075','Buchanan’s','Buchanan’s 18 Años 0,75 L','Mezcla de whiskies de grano y malta envejecidos en barricas de roble que solían contener jerez. Sedoso y delicado con sabores cítricos, nueces, miel y roble.',117.95,6,690),
W('wh-old-parr-18-075','Old Parr','Old Parr 18 Años 0,75 L','Elaborado a partir de combinaciones de hasta 40 whiskies de malta y granos. Elegante color dorado y fresco aroma a hojas verdes y roble.',98.95,12,1164),
W('wh-dewars-18-075','Dewar’s','Dewar’s 18 Años 0,75 L','Mezcla de doble añejamiento con 6 meses de casamiento en barricas de roble después de la maduración inicial. Con sabores de nuez y mazapán.',70,12,420),
W('wh-chivas-18-075','Chivas Regal','Chivas Regal 18 Años 0,75 L','Whisky complejo pero refinado. Una mezcla de 85 notas de sabor, perfectamente equilibrado y suave, con notas de chocolate negro.',135.60,6,803),
W('wh-jw-ultimate-075','Johnnie Walker','Ultimate 18 Años 0,75 L','Whisky de 18 años. Lujoso, cremoso y con notas de miel, tributo a la unión armoniosa entre los whiskies Speyside y Highland.',109.90,null,null),
W('wh-jw-platinum-075','Johnnie Walker','Platinum Label 0,75 L','Edición limitada. Selección de whiskies de single malt y grano con un mínimo de 18 años de reserva. Blended contemporáneo para paladares exigentes.',255,null,null),
W('wh-glenfiddich-18-075','Glenfiddich','Glenfiddich 18 Años 0,75 L','La fina madera tipo Olorosa y el roble americano maduran esta rica, afrutada y sólida expresión de roble. Cada lote es numerado individualmente.',148.50,6,1764),
W('wh-macallan-double-18-075','Macallan','Macallan Double Cask 18 Años 0,75 L','Whisky de malta único perfectamente equilibrado, madurado durante 18 años en barricas de roble condimentadas con jerez americano y europeo.',485.50,null,null),
W('wh-macallan-sherry-18-075','Macallan','Macallan Sherry Oak 18 Años 0,75 L','Liderado por roble europeo sazonado con jerez. Sabores de jengibre, pasas remojadas, dátiles pegajosos y chocolate amargo.',1220,null,null),
W('wh-royal-salute-21-1l','Royal Salute','Royal Salute 21 Años 1 L','Color dorado profundo y elegante. Aroma de peras dulces, cítricos y flores de otoño; sabor suave y fresco con mermelada de naranja y peras frescas.',385,null,null),
W('wh-jw-xr21-075','Johnnie Walker','XR 21 Años 0,75 L','Mezclado con reserva exclusiva de raros whiskies de Johnnie Walker madurados por 21 años. Firme, balanceado y elegante, con miel, especias y toque ahumado.',170,null,null),
W('wh-buchanans-red-seal-075','Buchanan’s','Buchanan’s Red Seal 0,75 L','Madurado a la perfección. Mezcla de maltas escocesas con notas refinadas y suaves, equilibrio entre lo suave y lo complejo.',215.90,null,null),
W('wh-jw-blue-075','Johnnie Walker','Etiqueta Azul 0,75 L','En su fórmula intervienen 16 whiskies diferentes, todos con una crianza de entre 21 a 50 años en barrica. Creado con barricas seleccionadas a mano.',342.90,null,null),
W('wh-jw-blue-1l','Johnnie Walker','Etiqueta Azul 1 L','En su fórmula intervienen 16 whiskies diferentes, todos con una crianza de entre 21 a 50 años en barrica. Creado con barricas seleccionadas a mano.',null,null,null),
W('wh-jw-blue-umami-075','Johnnie Walker','Etiqueta Azul Elusive Umami Edición Limitada 0,75 L','Umami, expresión pionera inspirada en el enigmático sabor también conocido como el quinto sabor.',460,null,null),
W('wh-jw-blue-xordinaire-1l','Johnnie Walker','Etiqueta Azul Xordinaire 1 L','Lujoso whisky escocés mezclado creado utilizando sólo 1 de cada 10.000 barricas de incomparables reservas de whisky escocés añejo.',823.50,null,null),
W('wh-cattos-25-075','Catto’s','Catto’s 25 Años 0,75 L','Un cuarto de siglo para madurar los mejores whiskies en barricas de roble americano Ex-bourbon y Ex-jerez cuidadosamente seleccionadas.',200,null,null),
W('wh-hibiki-075','Hibiki Suntory','Hibiki Suntory 0,75 L','Seductor, floreciente y sutil. Celebra el arte de mezcla y artesanía de House of Suntory. Final largo con un toque de Mizunara.',185,null,null),

W('wh-100-pipers-075','100 Pipers','100 Pipers 0,75 L','Whisky tipo blended, con más de 30 tipos de whisky de malta. Color dorado intenso, fragancia a roble y notas de caramelo.',13,12,135),
W('wh-glen-garvie-075','Glen Garvie','Glen Garvie 0,75 L','Whisky elaborado en Escocia a partir de cereales, fermentado y destilado. Envejecido en barricas de roble durante al menos 3 años.',11.50,12,132),
W('wh-king-queens-1l','King of Queen’s','King of Queen’s 1 L','Mezcla de whiskies de grano y malta de Escocia, con maltas de Speyside y Highland. Cada barrica se madura un mínimo de 3 años.',14.75,12,170),
W('wh-sir-edwards-075','Sir Edward’s','Sir Edward’s 0,75 L','Whisky blended con un mínimo de 3 años en barricas. Redondo y especiado, con fruta seca y sutiles notas de roble.',9.90,12,108),
W('wh-highland-queen-075','Highland Queen','Highland Queen 0,75 L','Color ámbar miel. Aromas dulces con miel, manzanas y caramelo. Sabor de cuerpo ligero y dulce.',13.75,12,150),
W('wh-glen-scanlan-1l','Glen Scanlan','Glen Scanlan 1 L','Destilado de cebada malteada seleccionada y mezclado con granos escoceses. Pasa 3 años en barricas.',18.90,12,210),
W('wh-kelvin-bridge-075','Kelvin Bridge','Kelvin Bridge 0,75 L','Especialmente mezclado para disfrutarlo en cualquier momento. Excelente como trago solo o con hielo.',12,12,140),
W('wh-glen-simon-075','Glen Simón','Glen Simón 0,75 L','Whisky escocés blend producido a partir de alcoholes destilados seleccionados, con sabor amaderado y toques de vainilla, frutas y especias.',12,12,144),
W('wh-mcivor-075','McIvor','McIvor 0,75 L','Especialmente mezclado para disfrutarlo en cualquier momento. Excelente solo o con hielo.',9,12,104),
W('wh-sir-albert-075','Sir Albert','Sir Albert 0,75 L','Limpio, suave, con profundo sabor a malta; whiskies maduros de varias destilerías de Escocia cuidadosamente mezclados.',10.50,12,117),
W('wh-consulate-075','Consulate','Consulate 0,75 L','Whisky escocés mezclado 100% con whiskies escoceses madurados, mezclado y enviado por Hamish Robertson & Co. Ltd, Glasgow.',11,12,120),
W('wh-old63-075','Old 63','Old 63 0,75 L','Whisky elaborado con selección de malta escocesa y cereales venezolanos, añejado en barrica de roble.',10.75,12,120),
W('wh-sir-xpecial-070','Sir Xpecial','Sir Xpecial 0,70 L','Mezcla de finas maltas y granos que junto a su maduración en barriles de roble da origen a un whisky equilibrado.',11.50,6,64.50),
W('wh-sir-xpecial-10barrels-075','Sir Xpecial','Sir Xpecial Edición Especial 10 Barrels 0,75 L','Añejado primero en barriles que tuvieron Bourbon durante más de 9 años y terminado en barriles ex-ron durante 10 meses.',12.40,6,67),
W('wh-mac-arthurs-075','Mac Arthur’s','Mac Arthur’s 0,75 L','Whisky de cuerpo medio. Mezcla suavemente aromática con paladar suave y final fresco y persistente.',9.50,12,108),
W('wh-hunting-lodge-075','Hunting Lodge','Hunting Lodge 0,75 L','Whisky suave y elegante, envejecido en barricas de roble durante 3 años, con whisky seleccionado de distintas regiones de Escocia.',10.50,12,123),
W('wh-dunfife-075','Dunfife','Dunfife 0,75 L','Whisky con mezclas de añejamiento mínimo de 5 años. Excelente solo o con hielo.',13,12,145),
W('wh-highland-breeze-075','Highland Breeze','Highland Breeze 0,75 L','Mezcla de whiskies de diferentes destilerías, elaborada con maíz o trigo y complementada con centeno, cebada o malta de cebada.',9.65,12,110),
W('wh-donald-blend-075','Donald Blend','Donald Blend 0,75 L','Licor de whisky elaborado con maltas de productores de Escocia y mezcladas con alcoholes neutros.',8,12,null),
W('wh-winner-reserva-075','Winner','Winner Reserva Especial 0,75 L','Mezcla de whiskies de mínimo 2 años en barrica. Perfecto a las rocas, con agua o en cocteles.',6,12,66),
W('wh-john-barr-1l','John Barr','John Barr 1 L','Whisky joven de 3 años de añejamiento en barricas de Jerez, con aromas de chocolate, manzana dulce horneada y pan recién horneado.',19.75,12,229),

W('wh-jack-1l','Jack Daniel’s','Jack Daniel’s 1 L','Añejado en barricas de su propia creación, sin añejamiento prefijado; está listo cuando los catadores de la casa así lo indican.',46.70,null,null),
W('wh-jack-apple-1l','Jack Daniel’s','Jack Daniel’s Apple 1 L','Carácter de Jack Daniel’s Tennessee junto con manzana verde para un sabor fresco, gratificante y muy suave.',39.50,12,456),
W('wh-jack-fire-1l','Jack Daniel’s','Jack Daniel’s Fire 1 L','Combina un ardiente licor de canela con el suave carácter de Jack Daniel’s Old No. 7 para un final encendido.',39.50,12,456),
W('wh-jack-honey-1l','Jack Daniel’s','Jack Daniel’s Honey 1 L','Mezcla de Jack Daniel’s Tennessee y un licor de miel único para un sabor inconfundible.',39.50,12,456),
W('wh-yellow-premium-070','Yellow Rose','Yellow Rose Premium American 0,70 L','Whisky artesanal elaborado en Houston, Texas, inspirado en la leyenda de Emily West, The Yellow Rose of Texas.',69.90,null,null),
W('wh-yellow-rye-070','Yellow Rose','Yellow Rose Rye 0,70 L','Producción limitada y lotes pequeños. Elaborado con 95% de Rye (centeno), un clásico estadounidense para cocteles finos.',51.50,null,null),
W('wh-yellow-harris-070','Yellow Rose','Yellow Rose Harris Bourbon 0,70 L','Hecho a mano y destilado en maceta en Houston, Texas, con granos 100% cultivados en Texas.',59.50,null,null),
W('wh-yellow-outlaw-070','Yellow Rose','Yellow Rose Outlaw Bourbon 0,70 L','Hecho 100% de maíz amarillo de Texas y añejado en pequeños barriles de roble americano en Houston.',null,null,null),
W('wh-meyers-070','Meyer’s','Meyer’s Le Whisky Alsacien 0,70 L','Mezcla de whisky de grano y malta pura con nariz fresca y fragante, cuerpo redondo y ligeramente almibarado y reflejos de cobre.',115,null,null),

W('wh-buchanans-master-075','Buchanan’s','Buchanan’s Master 0,75 L','Mezcla de maltas, al menos una de cada región de Escocia, seleccionada a mano. Notas de hierbas y cítricos.',52.90,12,612),
W('wh-buchanans-master-1l','Buchanan’s','Buchanan’s Master 1 L','Mezcla de maltas, al menos una de cada región de Escocia, seleccionada a mano. Notas de hierbas y cítricos.',null,12,null),
W('wh-buchanans-two-souls-075','Buchanan’s','Buchanan’s Two Souls 0,75 L','Primer whisky escocés terminado en barricas de tequila Don Julio. Ámbar intenso, con dulzor de Buchanan’s y notas herbales de Don Julio.',63.90,12,725),
W('wh-buchanans-pineapple-075','Buchanan’s','Buchanan’s Pineapple 0,75 L','Mezcla de whisky escocés con sabores naturales y piña, pensada para una experiencia de cócteles.',84.50,12,984),
W('wh-jw-double-black-075','Johnnie Walker','Double Black 0,75 L','Inspirado en Black Label, mezcla de whiskies escoceses de malta envejecidos y ahumados y maltas maduradas en barricas de roble carbonizadas.',87.95,12,516),
W('wh-jw-got-075','Johnnie Walker','Game of Thrones 0,75 L','Whisky rico y picante inspirado en Game Of Thrones, con humo sutil, frutos rojos, humo dulce y especias.',45,12,528),
W('wh-jw-black-200-075','Johnnie Walker','Etiqueta Negra 200 Years 0,75 L','Versión exclusiva por el aniversario de 200 años de la casa Walker.',58.50,12,684),
W('wh-jw-gold-reserve-1l','Johnnie Walker','Edición Especial Gold Label Reserve 1 L','Suave mezcla para celebrar con estilo y lujo, con notas de vainilla y fruta oscura.',79.50,null,null),
W('wh-jw-lowlands-1l','Johnnie Walker','Black Label Lowlands Origin 1 L','Carácter de vainilla dulce y cremosa y notas de caramelo, elaborado con whiskies de pura malta y grano de las Tierras Bajas.',70,null,null),
W('wh-jw-bourbon-rye-1l','Johnnie Walker','Bourbon Cask & Rye Finish 1 L','Creado con whisky de cinco destilerías, envejecido en barricas de bourbon y afinado 6 meses en barricas de rye. Rico y suave, con miel y vainilla.',85,null,null),
W('wh-cutty-prohibition-075','Cutty Sark','Cutty Sark Prohibition 0,75 L','Destilado de color claro con matices de oro pálido. Homenaje a la época de la Ley Seca y al Capitán Bill McCoy.',48.50,6,258),
W('wh-monkey-075','Monkey Shoulder','Monkey Shoulder 0,75 L','Whisky blended malts escocés de tres maltas diseñado para alta coctelería, madurado en barricas de bourbon durante 6 meses.',41.90,6,243),
W('wh-monkey-1l','Monkey Shoulder','Monkey Shoulder 1 L','Whisky blended malts escocés de tres maltas diseñado para alta coctelería, madurado en barricas de bourbon durante 6 meses.',68.90,6,402),
W('wh-old-parr-silver-075','Old Parr','Old Parr Silver 0,75 L','Experiencia más suave y accesible, sin sacrificar la calidad de la marca. No tiene declaración de edad específica.',26.50,12,304),
W('wh-glenfiddich-ipa-075','Glenfiddich','Glenfiddich IPA 0,75 L','Elaborada en barriles de IPA, con notas cítricas picantes de manzana verde madura y sabor a lúpulo fresco.',85.50,null,null),
W('wh-glenfiddich-vat01-1l','Glenfiddich','Glenfiddich VAT 01 1 L','Whisky de pura malta que combina notas dulces y especiadas; madurado en roble americano, roble europeo y vino tinto.',98.50,null,null),
W('wh-glenfiddich-vat02-1l','Glenfiddich','Glenfiddich VAT 02 1 L','Madurado en barricas de Jerez de roble europeo; single malt de sabor suave y sedoso que evoluciona en copa.',110,null,null),
W('wh-glenmorangie-10-075','Glenmorangie','Glenmorangie 10 Years 0,75 L','Whisky delicado y versátil, elaborado en alambiques con altura de jirafa y envejecido durante 10 años en barricas de bourbon.',61,null,null),
W('wh-macallan-lumina-075','Macallan','Macallan Lumina 0,75 L','Single malt con exploración de sabores y texturas, desde notas vibrantes y frescas hasta toques intensos y pronunciados.',139.50,null,null),
W('wh-macallan-classic-cut-075','Macallan','Macallan Classic Cut 0,75 L','Madurado en una combinación única de barricas con roble europeo y americano para una experiencia de degustación única.',246.50,null,null),
];
