import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { products } from '@/src/data/products';
import { colors } from '@/src/theme';

const ORDERS_KEY='celicor_orders_v1';

export default function AdminScreen(){
  const [orders,setOrders]=useState<any[]>([]);
  useFocusEffect(useCallback(()=>{AsyncStorage.getItem(ORDERS_KEY).then(v=>setOrders(v?JSON.parse(v):[])).catch(()=>setOrders([]));},[]));
  const sales=useMemo(()=>orders.reduce((s,o)=>s+Number(o.total||0),0),[orders]);
  const active=orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length;

  return <SafeAreaView style={styles.safe}><View style={styles.nav}><Pressable style={styles.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={24} color={colors.navy}/></Pressable><View style={{flex:1,marginLeft:12}}><Text style={styles.navTitle}>Panel CELICOR</Text><Text style={styles.navSub}>Operaciones de la tienda</Text></View><View style={styles.adminBadge}><Text style={styles.adminText}>ADMIN</Text></View></View>
  <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.hero}><Text style={styles.heroKicker}>HOY</Text><Text style={styles.heroTitle}>Control de ventas y pedidos</Text><Text style={styles.heroCopy}>Esta V1 ya resume las órdenes creadas desde la app. La siguiente capa conecta inventario y edición directa con Supabase.</Text></View>
    <View style={styles.stats}><Stat icon="cash-outline" label="Ventas" value={`$${sales.toFixed(2)}`}/><Stat icon="receipt-outline" label="Pedidos" value={String(orders.length)}/><Stat icon="time-outline" label="Activos" value={String(active)}/><Stat icon="cube-outline" label="Productos" value={String(products.length)}/></View>

    <Text style={styles.section}>GESTIÓN</Text><View style={styles.group}><Menu icon="receipt-outline" title="Pedidos" sub="Aceptar, preparar y entregar"/><Menu icon="cube-outline" title="Productos e inventario" sub="Precio, stock, presentación y disponibilidad"/><Menu icon="pricetag-outline" title="Promociones y cupones" sub="Ofertas, banners y descuentos"/><Menu icon="bicycle-outline" title="Zonas de delivery" sub="Tarifas y mínimos de compra"/></View>

    <View style={styles.sectionRow}><Text style={styles.section}>PEDIDOS RECIENTES</Text><Text style={styles.small}>{orders.length}</Text></View>{orders.slice(0,5).map(o=><View style={styles.order} key={o.id}><View style={{flex:1}}><Text style={styles.orderTitle}>#{o.number} · {o.zone}</Text><Text style={styles.orderSub}>{o.items?.reduce((s:number,i:any)=>s+i.quantity,0)||0} productos · {o.payment}</Text></View><Text style={styles.orderTotal}>${Number(o.total).toFixed(2)}</Text></View>)}{!orders.length&&<View style={styles.empty}><Text style={styles.emptyText}>Todavía no hay pedidos creados en este dispositivo.</Text></View>}

    <Text style={styles.section}>CATÁLOGO CARGADO</Text>{products.slice(0,8).map(p=><View style={styles.product} key={p.id}><View style={styles.productVisual}><Text>🍾</Text></View><View style={{flex:1}}><Text style={styles.productBrand}>{p.brand}</Text><Text style={styles.productName}>{p.name} · {p.size}</Text></View><Text style={styles.productPrice}>${p.price.toFixed(2)}</Text></View>)}
  </ScrollView></SafeAreaView>
}

function Stat({icon,label,value}:{icon:any,label:string,value:string}){return <View style={styles.stat}><Ionicons name={icon} size={21} color={colors.orangeDark}/><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
function Menu({icon,title,sub}:{icon:any,title:string,sub:string}){return <Pressable style={styles.menu}><View style={styles.menuIcon}><Ionicons name={icon} size={21} color={colors.navy}/></View><View style={{flex:1}}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuSub}>{sub}</Text></View><Ionicons name="chevron-forward" size={19} color="#A3AAB5"/></Pressable>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},nav:{padding:18,paddingTop:12,flexDirection:'row',alignItems:'center'},back:{width:44,height:44,borderRadius:15,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},navTitle:{fontSize:18,fontWeight:'900',color:colors.navy},navSub:{fontSize:11,color:colors.muted,marginTop:2},adminBadge:{backgroundColor:colors.navy,borderRadius:999,paddingHorizontal:10,paddingVertical:7},adminText:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#fff'},content:{padding:18,paddingTop:2,paddingBottom:40},hero:{backgroundColor:colors.navy,borderRadius:24,padding:20},heroKicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:colors.orange},heroTitle:{fontSize:24,lineHeight:28,fontWeight:'900',color:'#fff',marginTop:6},heroCopy:{fontSize:12,lineHeight:18,color:'#C9D4E8',marginTop:8},stats:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',marginTop:12},stat:{width:'48.5%',backgroundColor:'#fff',borderRadius:18,padding:15,marginBottom:10,borderWidth:1,borderColor:colors.line},statValue:{fontSize:22,fontWeight:'900',color:colors.navy,marginTop:8},statLabel:{fontSize:11,fontWeight:'700',color:colors.muted,marginTop:2},section:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:colors.muted,marginTop:24,marginBottom:9},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},small:{fontSize:11,fontWeight:'900',color:colors.orangeDark,marginBottom:9},group:{backgroundColor:'#fff',borderRadius:20,overflow:'hidden',borderWidth:1,borderColor:colors.line},menu:{padding:14,flexDirection:'row',gap:12,alignItems:'center',borderBottomWidth:1,borderBottomColor:'#F0F1F4'},menuIcon:{width:40,height:40,borderRadius:13,backgroundColor:'#F3F5F9',alignItems:'center',justifyContent:'center'},menuTitle:{fontSize:14,fontWeight:'900',color:colors.text},menuSub:{fontSize:11,color:colors.muted,marginTop:2},order:{backgroundColor:'#fff',borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',marginBottom:8,borderWidth:1,borderColor:colors.line},orderTitle:{fontSize:13,fontWeight:'900',color:colors.text},orderSub:{fontSize:11,color:colors.muted,marginTop:3},orderTotal:{fontSize:17,fontWeight:'900',color:colors.navy},empty:{backgroundColor:'#fff',borderRadius:16,padding:18},emptyText:{fontSize:12,color:colors.muted,textAlign:'center'},product:{backgroundColor:'#fff',borderRadius:15,padding:11,flexDirection:'row',alignItems:'center',gap:10,marginBottom:7,borderWidth:1,borderColor:colors.line},productVisual:{width:38,height:44,borderRadius:11,backgroundColor:'#F5F7FB',alignItems:'center',justifyContent:'center'},productBrand:{fontSize:10,fontWeight:'900',color:colors.orangeDark,textTransform:'uppercase'},productName:{fontSize:12,fontWeight:'800',color:colors.text,marginTop:2},productPrice:{fontSize:14,fontWeight:'900',color:colors.navy}})
