import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, money, supabase } from '@/src/core';
import { useSession } from '@/src/state';
import { Brand, Notice } from '@/src/ui';
const next:any={assigned:'picked_up',picked_up:'on_route',on_route:'delivered'};const label:any={assigned:'Aceptar / recoger',picked_up:'Salir a ruta',on_route:'Marcar entregado',delivered:'Entregado'};
export default function Delivery(){const{session,profile}=useSession();const[jobs,setJobs]=useState<any[]>([]);const allowed=profile?.role==='driver'||profile?.role==='admin'||profile?.role==='staff';const load=async()=>{if(!session)return;let q=supabase.from('delivery_jobs').select('*,orders(*)').order('created_at',{ascending:false});if(profile?.role==='driver')q=q.eq('driver_id',session.user.id);const{data}=await q;setJobs(data||[])};useEffect(()=>{if(allowed)load()},[allowed,session?.user.id]);if(!allowed)return <SafeAreaView style={s.screen}><View style={{padding:22}}><Notice>Este panel es exclusivo para repartidores y administradores.</Notice></View></SafeAreaView>;const advance=async(j:any)=>{const status=next[j.status];if(!status)return;const patch:any={status};if(status==='picked_up')patch.picked_up_at=new Date().toISOString();if(status==='delivered')patch.delivered_at=new Date().toISOString();await supabase.from('delivery_jobs').update(patch).eq('id',j.id);if(status==='on_route')await supabase.from('orders').update({status:'out_for_delivery'}).eq('id',j.order_id);if(status==='delivered')await supabase.from('orders').update({status:'delivered'}).eq('id',j.order_id);load()};return <SafeAreaView style={s.screen}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={{fontSize:28}}>‹</Text></Pressable><Brand compact/><Text style={s.badge}>DELIVERY</Text></View><ScrollView contentContainerStyle={{padding:18,paddingBottom:60}}><Text style={s.title}>Mis entregas</Text><Text style={s.copy}>Pedidos asignados y ruta de entrega.</Text>{jobs.length===0?<View style={s.empty}><Text style={{fontSize:55}}>🛵</Text><Text style={s.emptyText}>No tienes entregas asignadas.</Text></View>:jobs.map(j=><View key={j.id} style={s.card}><View style={s.row}><Text style={s.number}>Pedido #{j.orders?.order_number}</Text><Text style={s.status}>{j.status}</Text></View><Text style={s.customer}>{j.orders?.customer_name}</Text><Text style={s.address}>📍 {j.orders?.address_text}</Text><Text style={s.address}>📞 {j.orders?.phone} · {money(j.orders?.total)}</Text><View style={s.actions}><Pressable style={s.call} onPress={()=>Linking.openURL(`tel:${j.orders?.phone}`)}><Text style={s.callText}>LLAMAR</Text></Pressable>{next[j.status]?<Pressable style={s.primary} onPress={()=>advance(j)}><Text style={s.primaryText}>{label[j.status].toUpperCase()}</Text></Pressable>:null}</View></View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},header:{height:65,paddingHorizontal:18,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},badge:{fontSize:9,fontWeight:'1000',backgroundColor:colors.green,color:'#fff',paddingHorizontal:9,paddingVertical:5,borderRadius:99},title:{fontSize:29,fontWeight:'1000'},copy:{color:colors.muted,marginTop:4,marginBottom:18},empty:{alignItems:'center',paddingTop:80},emptyText:{fontWeight:'900',marginTop:12},card:{backgroundColor:'#fff',borderRadius:22,padding:17,marginBottom:12},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},number:{fontWeight:'1000',fontSize:16},status:{fontSize:9,fontWeight:'1000',backgroundColor:'#E7F8F0',color:colors.green,paddingHorizontal:9,paddingVertical:5,borderRadius:99,textTransform:'uppercase'},customer:{fontWeight:'900',marginTop:13},address:{fontSize:12,color:colors.muted,marginTop:5,lineHeight:18},actions:{flexDirection:'row',gap:8,marginTop:15},call:{paddingHorizontal:16,paddingVertical:13,borderRadius:14,borderWidth:1,borderColor:colors.line},callText:{fontSize:10,fontWeight:'1000',color:colors.navy},primary:{flex:1,backgroundColor:colors.orange,padding:13,borderRadius:14,alignItems:'center'},primaryText:{fontSize:10,fontWeight:'1000',color:colors.navy}});
