import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { colors } from '@/src/theme';

export default function OrderSuccess(){
  const {number,total}=useLocalSearchParams<{number:string,total:string}>();
  return <SafeAreaView style={styles.safe}><View style={styles.card}><View style={styles.icon}><Ionicons name="checkmark" size={46} color="#fff"/></View><Text style={styles.title}>¡Pedido recibido!</Text><Text style={styles.copy}>Estamos preparando tu orden. Puedes revisar su estado desde la sección Pedidos.</Text><View style={styles.info}><Text style={styles.label}>Pedido</Text><Text style={styles.value}>#{number}</Text><Text style={[styles.label,{marginTop:14}]}>Total</Text><Text style={styles.total}>${total}</Text></View><Pressable style={styles.primary} onPress={()=>router.replace('/(tabs)/orders')}><Text style={styles.primaryText}>VER MI PEDIDO</Text></Pressable><Pressable style={styles.secondary} onPress={()=>router.replace('/(tabs)')}><Text style={styles.secondaryText}>Volver al inicio</Text></Pressable></View></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.navy,padding:22,justifyContent:'center'},card:{backgroundColor:'#fff',borderRadius:30,padding:28,alignItems:'center'},icon:{width:86,height:86,borderRadius:43,backgroundColor:colors.success,alignItems:'center',justifyContent:'center',marginBottom:20},title:{fontSize:28,fontWeight:'900',color:colors.navy},copy:{fontSize:14,lineHeight:21,textAlign:'center',color:colors.muted,marginTop:8},info:{width:'100%',backgroundColor:colors.background,borderRadius:18,padding:18,marginTop:22},label:{fontSize:11,fontWeight:'800',color:colors.muted,textTransform:'uppercase'},value:{fontSize:22,fontWeight:'900',color:colors.text,marginTop:3},total:{fontSize:26,fontWeight:'900',color:colors.navy,marginTop:3},primary:{width:'100%',backgroundColor:colors.orange,borderRadius:16,paddingVertical:16,alignItems:'center',marginTop:20},primaryText:{fontSize:13,fontWeight:'900',color:colors.navy},secondary:{padding:14},secondaryText:{fontSize:13,fontWeight:'800',color:colors.muted}})
