import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useCart } from '@/src/store/cart';
import { colors } from '@/src/theme';

export default function CartScreen(){
  const {items,setQty,remove,subtotal,count}=useCart();
  const delivery=0;
  const total=subtotal+delivery;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.title}>Tu carrito</Text><Text style={styles.subtitle}>{count} {count===1?'producto':'productos'}</Text></View>{items.length>0&&<Pressable onPress={()=>items.forEach(i=>remove(i.product.id))}><Text style={styles.clear}>Vaciar</Text></Pressable>}</View>
  {!items.length?<View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="cart-outline" size={42} color={colors.navy}/></View><Text style={styles.emptyTitle}>Tu carrito está vacío</Text><Text style={styles.emptyText}>Agrega tus botellas favoritas y vuelve por aquí.</Text><Pressable style={styles.primary} onPress={()=>router.push('/(tabs)/search')}><Text style={styles.primaryText}>VER CATÁLOGO</Text></Pressable></View>:
  <><ScrollView contentContainerStyle={styles.list}>{items.map(({product,quantity})=><View key={product.id} style={styles.item}><View style={styles.visual}><Text style={{fontSize:36}}>🍾</Text></View><View style={{flex:1}}><Text style={styles.brand}>{product.brand}</Text><Text style={styles.name}>{product.name}</Text><Text style={styles.size}>{product.size}</Text><Text style={styles.price}>${product.price.toFixed(2)}</Text></View><View style={styles.qty}><Pressable onPress={()=>setQty(product.id,quantity-1)} style={styles.qtyBtn}><Ionicons name="remove" size={18} color={colors.navy}/></Pressable><Text style={styles.qtyText}>{quantity}</Text><Pressable onPress={()=>setQty(product.id,quantity+1)} style={styles.qtyBtn}><Ionicons name="add" size={18} color={colors.navy}/></Pressable></View></View>)}</ScrollView>
  <View style={styles.summary}><View style={styles.line}><Text style={styles.label}>Subtotal</Text><Text style={styles.value}>${subtotal.toFixed(2)}</Text></View><View style={styles.line}><Text style={styles.label}>Delivery</Text><Text style={styles.delivery}>Se calcula al elegir zona</Text></View><View style={styles.divider}/><View style={styles.line}><Text style={styles.totalLabel}>Total estimado</Text><Text style={styles.total}>${total.toFixed(2)}</Text></View><Pressable style={styles.primary} onPress={()=>router.push('/checkout')}><Text style={styles.primaryText}>CONTINUAR PEDIDO</Text><Ionicons name="arrow-forward" size={18} color={colors.navy}/></Pressable></View></>}
  </SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{padding:18,paddingTop:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:30,fontWeight:'900',color:colors.navy},subtitle:{fontSize:13,color:colors.muted,marginTop:3},clear:{fontSize:12,fontWeight:'800',color:colors.danger},list:{paddingHorizontal:18,paddingBottom:260},item:{backgroundColor:'#fff',borderRadius:20,padding:12,marginBottom:10,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:colors.line},visual:{width:66,height:78,borderRadius:14,backgroundColor:'#F5F7FB',alignItems:'center',justifyContent:'center'},brand:{fontSize:10,fontWeight:'900',color:colors.orangeDark,textTransform:'uppercase'},name:{fontSize:15,fontWeight:'900',color:colors.text,marginTop:2},size:{fontSize:11,color:colors.muted,marginTop:2},price:{fontSize:15,fontWeight:'900',color:colors.navy,marginTop:6},qty:{flexDirection:'row',alignItems:'center',gap:8},qtyBtn:{width:30,height:30,borderRadius:10,backgroundColor:'#F1F3F7',alignItems:'center',justifyContent:'center'},qtyText:{minWidth:18,textAlign:'center',fontWeight:'900',color:colors.text},summary:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:'#fff',padding:18,paddingBottom:24,borderTopLeftRadius:26,borderTopRightRadius:26,borderTopWidth:1,borderColor:colors.line},line:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10},label:{color:colors.muted,fontSize:13},value:{color:colors.text,fontWeight:'800'},delivery:{color:colors.orangeDark,fontSize:12,fontWeight:'800'},divider:{height:1,backgroundColor:colors.line,marginVertical:6,marginBottom:14},totalLabel:{fontSize:16,fontWeight:'900',color:colors.text},total:{fontSize:22,fontWeight:'900',color:colors.navy},primary:{marginTop:12,backgroundColor:colors.orange,borderRadius:16,paddingVertical:16,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},primaryText:{fontWeight:'900',color:colors.navy,fontSize:13},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:34},emptyIcon:{width:82,height:82,borderRadius:26,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',marginBottom:18},emptyTitle:{fontSize:22,fontWeight:'900',color:colors.text},emptyText:{textAlign:'center',fontSize:13,lineHeight:20,color:colors.muted,marginTop:7,marginBottom:10}})
