import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, money, supabase } from '@/src/core';
import { useSession } from '@/src/state';
import { ScreenTitle } from '@/src/ui';
const labels:any={pending:'Recibido',confirmed:'Confirmado',preparing:'Preparando',ready:'Listo',out_for_delivery:'En camino',delivered:'Entregado',cancelled:'Cancelado'};
export default function Orders(){const{session}=useSession();const[orders,setOrders]=useState<any[]>([]);useEffect(()=>{if(!session){setOrders([]);return;}supabase.from('orders').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false}).then(({data})=>setOrders(data||[]));},[session?.user.id]);return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={{padding:18,paddingBottom:100}}><ScreenTitle title="Mis pedidos" subtitle="Consulta el estado de tus compras."/>{!session?<View style={s.empty}><Text style={{fontSize:50}}>🧾</Text><Text style={s.emptyTitle}>Inicia sesión para ver tus pedidos</Text><Pressable style={s.button} onPress={()=>router.push('/login' as any)}><Text style={s.buttonText}>ENTRAR</Text></Pressable></View>:orders.length===0?<View style={s.empty}><Text style={{fontSize:50}}>🥃</Text><Text style={s.emptyTitle}>Aún no tienes pedidos</Text></View>:orders.map(o=><View key={o.id} style={s.card}><View style={s.row}><Text style={s.number}>Pedido #{o.order_number}</Text><Text style={[s.status,o.status==='delivered'&&{backgroundColor:'#E7F8F0',color:colors.green}]}>{labels[o.status]||o.status}</Text></View><Text style={s.date}>{new Date(o.created_at).toLocaleString()}</Text><View style={s.row}><Text style={s.mode}>{o.delivery_mode==='pickup'?'🏪 Retiro':'🛵 Delivery'}</Text><Text style={s.total}>{money(o.total)}</Text></View></View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.bg},empty:{alignItems:'center',paddingTop:80},emptyTitle:{fontSize:18,fontWeight:'900',color:colors.text,marginTop:12,textAlign:'center'},button:{marginTop:18,backgroundColor:colors.navy,paddingHorizontal:28,paddingVertical:14,borderRadius:15},buttonText:{color:'#fff',fontWeight:'900'},card:{backgroundColor:'#fff',padding:17,borderRadius:20,marginBottom:12},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},number:{fontSize:16,fontWeight:'1000'},status:{backgroundColor:'#FFF1CC',color:'#7D5600',paddingHorizontal:10,paddingVertical:6,borderRadius:99,fontSize:10,fontWeight:'900'},date:{fontSize:11,color:colors.muted,marginVertical:10},mode:{fontWeight:'800',color:colors.text},total:{fontSize:19,fontWeight:'1000',color:colors.navy}});
