import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors } from '@/src/theme';

const KEY='celicor_orders_v1';
const statusLabel:Record<string,string>={pending:'Recibido',confirmed:'Confirmado',preparing:'Preparando',ready:'Listo',out_for_delivery:'En camino',delivered:'Entregado',cancelled:'Cancelado'};

export default function OrdersScreen(){
  const [orders,setOrders]=useState<any[]>([]);
  useFocusEffect(useCallback(()=>{AsyncStorage.getItem(KEY).then(v=>setOrders(v?JSON.parse(v):[])).catch(()=>setOrders([]));},[]));
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Text style={styles.title}>Mis pedidos</Text><Text style={styles.subtitle}>Seguimiento e historial de compras.</Text></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{orders.length===0?<View style={styles.empty}><View style={styles.icon}><Ionicons name="receipt-outline" size={38} color={colors.navy}/></View><Text style={styles.emptyTitle}>Aún no tienes pedidos</Text><Text style={styles.emptyText}>Cuando hagas tu primera compra aparecerá aquí.</Text></View>:orders.map(o=><View key={o.id} style={styles.card}><View style={styles.top}><View><Text style={styles.order}>Pedido #{o.number}</Text><Text style={styles.date}>{new Date(o.createdAt).toLocaleString()}</Text></View><View style={styles.status}><View style={styles.dot}/><Text style={styles.statusText}>{statusLabel[o.status]||o.status}</Text></View></View><View style={styles.divider}/><View style={styles.row}><Ionicons name={o.mode==='delivery'?'bicycle-outline':'storefront-outline'} size={19} color={colors.orangeDark}/><Text style={styles.rowText}>{o.zone}</Text></View><View style={styles.row}><Ionicons name="card-outline" size={19} color={colors.orangeDark}/><Text style={styles.rowText}>{o.payment}</Text></View><View style={styles.items}><Text style={styles.itemsText}>{o.items.reduce((s:number,i:any)=>s+i.quantity,0)} productos</Text><Text style={styles.total}>${Number(o.total).toFixed(2)}</Text></View></View>)}</ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{padding:18,paddingTop:14},title:{fontSize:30,fontWeight:'900',color:colors.navy},subtitle:{fontSize:13,color:colors.muted,marginTop:3},content:{padding:18,paddingTop:4,paddingBottom:32},card:{backgroundColor:'#fff',borderRadius:20,padding:16,marginBottom:11,borderWidth:1,borderColor:colors.line},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12},order:{fontSize:16,fontWeight:'900',color:colors.text},date:{fontSize:11,color:colors.muted,marginTop:4},status:{backgroundColor:'#EAF8F3',paddingHorizontal:10,paddingVertical:7,borderRadius:999,flexDirection:'row',alignItems:'center',gap:6},dot:{width:7,height:7,borderRadius:4,backgroundColor:colors.success},statusText:{fontSize:10,fontWeight:'900',color:colors.success},divider:{height:1,backgroundColor:colors.line,marginVertical:14},row:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:8},rowText:{fontSize:12,color:colors.muted,flex:1},items:{marginTop:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},itemsText:{fontSize:12,fontWeight:'800',color:colors.text},total:{fontSize:20,fontWeight:'900',color:colors.navy},empty:{alignItems:'center',paddingTop:100,paddingHorizontal:30},icon:{width:80,height:80,borderRadius:25,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},emptyTitle:{fontSize:20,fontWeight:'900',color:colors.text,marginTop:16},emptyText:{textAlign:'center',fontSize:13,lineHeight:20,color:colors.muted,marginTop:6}})
