import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors } from '@/src/theme';

const Item=({icon,title,subtitle,onPress}:{icon:any,title:string,subtitle?:string,onPress?:()=>void})=><Pressable style={styles.item} onPress={onPress}><View style={styles.itemIcon}><Ionicons name={icon} size={21} color={colors.navy}/></View><View style={{flex:1}}><Text style={styles.itemTitle}>{title}</Text>{subtitle&&<Text style={styles.itemSub}>{subtitle}</Text>}</View><Ionicons name="chevron-forward" size={19} color="#A3AAB5"/></Pressable>;

export default function ProfileScreen(){
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>Perfil</Text><Text style={styles.subtitle}>Tu cuenta, direcciones y ayuda.</Text>
    <View style={styles.account}><View style={styles.avatar}><Ionicons name="person" size={28} color={colors.navy}/></View><View style={{flex:1}}><Text style={styles.accountTitle}>Compra más rápido</Text><Text style={styles.accountCopy}>Inicia sesión para guardar direcciones y sincronizar pedidos.</Text></View><Pressable style={styles.login} onPress={()=>router.push('/login')}><Text style={styles.loginText}>ENTRAR</Text></Pressable></View>
    <Text style={styles.section}>MI CUENTA</Text><View style={styles.group}><Item icon="location-outline" title="Direcciones" subtitle="Casa, oficina y otras direcciones"/><Item icon="heart-outline" title="Favoritos" subtitle="Tus botellas guardadas"/><Item icon="notifications-outline" title="Notificaciones" subtitle="Promociones y estado de pedidos"/></View>
    <Text style={styles.section}>CELICOR</Text><View style={styles.group}><Item icon="logo-whatsapp" title="WhatsApp" subtitle="+58 424-2583500" onPress={()=>Linking.openURL('https://wa.me/584242583500')}/><Item icon="call-outline" title="Llamar a la tienda" subtitle="+58 212-2634948" onPress={()=>Linking.openURL('tel:+582122634948')}/><Item icon="location-outline" title="La Castellana" subtitle="Av. Blandín con Calle Mata de Coco, Caracas"/></View>
    <Text style={styles.section}>GESTIÓN</Text><View style={styles.group}><Item icon="grid-outline" title="Panel administrativo" subtitle="Productos, stock, pedidos y ventas" onPress={()=>router.push('/admin')}/></View>
    <Text style={styles.version}>CELICOR La Castellana · App v0.1.0</Text></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:18,paddingTop:14,paddingBottom:36},title:{fontSize:30,fontWeight:'900',color:colors.navy},subtitle:{fontSize:13,color:colors.muted,marginTop:3},account:{marginTop:20,backgroundColor:colors.navy,borderRadius:22,padding:16,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:52,height:52,borderRadius:18,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},accountTitle:{fontSize:15,fontWeight:'900',color:'#fff'},accountCopy:{fontSize:11,lineHeight:16,color:'#C9D4E8',marginTop:3},login:{backgroundColor:colors.orange,borderRadius:12,paddingHorizontal:12,paddingVertical:10},loginText:{fontSize:10,fontWeight:'900',color:colors.navy},section:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:colors.muted,marginTop:24,marginBottom:9},group:{backgroundColor:'#fff',borderRadius:20,overflow:'hidden',borderWidth:1,borderColor:colors.line},item:{padding:14,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#F0F1F4'},itemIcon:{width:40,height:40,borderRadius:13,backgroundColor:'#F3F5F9',alignItems:'center',justifyContent:'center'},itemTitle:{fontSize:14,fontWeight:'800',color:colors.text},itemSub:{fontSize:11,color:colors.muted,marginTop:2},version:{textAlign:'center',fontSize:11,color:'#9CA3AF',marginTop:26}})
