-- CELICOR La Castellana — fresh mobile commerce schema
-- Apply this migration to the connected Supabase project after the fresh app reset.

drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.create_order(uuid,uuid,text,text,text,text,jsonb) cascade;
drop function if exists public.create_order(text,text,text,uuid,text,jsonb,text) cascade;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.is_staff() cascade;
drop function if exists public.set_updated_at() cascade;

drop table if exists public.delivery_jobs cascade;
drop table if exists public.order_items cascade;
drop table if exists public.orders cascade;
drop table if exists public.payment_links cascade;
drop table if exists public.addresses cascade;
drop table if exists public.products cascade;
drop table if exists public.categories cascade;
drop table if exists public.app_settings cascade;
drop table if exists public.profiles cascade;

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text,full_name text,phone text,role text not null default 'customer' check(role in('customer','admin','staff','driver')),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,emoji text not null default '🍾',sort_order int not null default 0,active boolean not null default true,created_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(),category_id uuid references public.categories(id) on delete set null,brand text,name text not null,slug text not null unique,description text,size text,image_url text,price numeric(12,2) not null default 0 check(price>=0),box_qty int,box_price numeric(12,2),stock int not null default 0 check(stock>=0),featured boolean not null default false,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payment_links(id uuid primary key default gen_random_uuid(),label text not null,provider text not null,url text not null,instructions text,active boolean not null default true,sort_order int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.addresses(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,label text not null default 'Casa',address_line text not null,reference text,is_default boolean not null default false,created_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),order_number bigint generated always as identity unique,user_id uuid not null references public.profiles(id) on delete restrict,customer_name text not null,phone text not null,address_text text,delivery_mode text not null default 'delivery' check(delivery_mode in('delivery','pickup')),status text not null default 'pending' check(status in('pending','confirmed','preparing','ready','out_for_delivery','delivered','cancelled')),payment_link_id uuid references public.payment_links(id) on delete set null,payment_reference text,payment_status text not null default 'pending' check(payment_status in('pending','reported','paid','rejected','refunded')),subtotal numeric(12,2) not null default 0,delivery_fee numeric(12,2) not null default 0,total numeric(12,2) not null default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id) on delete set null,product_name text not null,unit_price numeric(12,2) not null,quantity int not null check(quantity>0),line_total numeric(12,2) not null,created_at timestamptz not null default now());
create table public.delivery_jobs(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.orders(id) on delete cascade,driver_id uuid references public.profiles(id) on delete set null,status text not null default 'unassigned' check(status in('unassigned','assigned','picked_up','on_route','delivered','cancelled')),eta_minutes int,notes text,assigned_at timestamptz,picked_up_at timestamptz,delivered_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.app_settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now());

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now();return new;end $$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at();create trigger products_updated before update on public.products for each row execute function public.set_updated_at();create trigger payment_links_updated before update on public.payment_links for each row execute function public.set_updated_at();create trigger orders_updated before update on public.orders for each row execute function public.set_updated_at();create trigger delivery_jobs_updated before update on public.delivery_jobs for each row execute function public.set_updated_at();

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name,phone) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.phone,new.raw_user_meta_data->>'phone')) on conflict(id) do update set email=excluded.email;return new;end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
insert into public.profiles(id,email,full_name,phone) select id,email,coalesce(raw_user_meta_data->>'full_name',''),coalesce(phone,raw_user_meta_data->>'phone') from auth.users on conflict(id) do nothing;

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in('admin','staff') and active=true); $$;

create or replace function public.create_order(p_customer_name text,p_phone text,p_address_text text,p_payment_link_id uuid,p_notes text,p_items jsonb,p_delivery_mode text default 'delivery') returns jsonb language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid();v_subtotal numeric(12,2):=0;v_delivery_fee numeric(12,2):=0;v_total numeric(12,2):=0;v_order_id uuid;v_order_number bigint;v_item jsonb;v_product public.products%rowtype;v_qty int;
begin
if v_uid is null then raise exception 'Authentication required';end if;if trim(coalesce(p_customer_name,''))='' then raise exception 'Customer name required';end if;if trim(coalesce(p_phone,''))='' then raise exception 'Phone required';end if;if p_delivery_mode not in('delivery','pickup') then raise exception 'Invalid delivery mode';end if;if p_delivery_mode='delivery' and trim(coalesce(p_address_text,''))='' then raise exception 'Delivery address required';end if;if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Cart is empty';end if;
for v_item in select value from jsonb_array_elements(p_items) loop v_qty:=greatest(1,coalesce((v_item->>'quantity')::int,1));select * into v_product from public.products where id=(v_item->>'product_id')::uuid and active=true for update;if not found then raise exception 'Product unavailable';end if;if v_product.stock<v_qty then raise exception 'Insufficient stock for %',v_product.name;end if;v_subtotal:=v_subtotal+v_product.price*v_qty;end loop;
select coalesce((value->>'fee')::numeric,0) into v_delivery_fee from public.app_settings where key='delivery';if not found or p_delivery_mode='pickup' then v_delivery_fee:=0;end if;v_total:=v_subtotal+v_delivery_fee;
insert into public.orders(user_id,customer_name,phone,address_text,delivery_mode,payment_link_id,subtotal,delivery_fee,total,notes) values(v_uid,trim(p_customer_name),trim(p_phone),nullif(trim(coalesce(p_address_text,'')),''),p_delivery_mode,p_payment_link_id,v_subtotal,v_delivery_fee,v_total,p_notes) returning id,order_number into v_order_id,v_order_number;
for v_item in select value from jsonb_array_elements(p_items) loop v_qty:=greatest(1,coalesce((v_item->>'quantity')::int,1));select * into v_product from public.products where id=(v_item->>'product_id')::uuid;insert into public.order_items(order_id,product_id,product_name,unit_price,quantity,line_total) values(v_order_id,v_product.id,concat_ws(' ',v_product.brand,v_product.name),v_product.price,v_qty,v_product.price*v_qty);update public.products set stock=stock-v_qty where id=v_product.id;end loop;if p_delivery_mode='delivery' then insert into public.delivery_jobs(order_id) values(v_order_id);end if;return jsonb_build_object('id',v_order_id,'order_number',v_order_number,'total',v_total);end $$;
revoke all on function public.create_order(text,text,text,uuid,text,jsonb,text) from public;grant execute on function public.create_order(text,text,text,uuid,text,jsonb,text) to authenticated;

alter table public.profiles enable row level security;alter table public.categories enable row level security;alter table public.products enable row level security;alter table public.payment_links enable row level security;alter table public.addresses enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.delivery_jobs enable row level security;alter table public.app_settings enable row level security;
create policy profiles_read on public.profiles for select using(id=auth.uid() or public.is_staff());create policy profiles_self_update on public.profiles for update using(id=auth.uid() or public.is_staff()) with check(id=auth.uid() or public.is_staff());
create policy categories_read on public.categories for select using(active=true or public.is_staff());create policy categories_write on public.categories for all using(public.is_staff()) with check(public.is_staff());
create policy products_read on public.products for select using(active=true or public.is_staff());create policy products_write on public.products for all using(public.is_staff()) with check(public.is_staff());
create policy payment_read on public.payment_links for select using(active=true or public.is_staff());create policy payment_write on public.payment_links for all using(public.is_staff()) with check(public.is_staff());
create policy addresses_own on public.addresses for all using(user_id=auth.uid() or public.is_staff()) with check(user_id=auth.uid() or public.is_staff());
create policy orders_read on public.orders for select using(user_id=auth.uid() or public.is_staff() or exists(select 1 from public.delivery_jobs d where d.order_id=id and d.driver_id=auth.uid()));create policy orders_update on public.orders for update using(public.is_staff()) with check(public.is_staff());
create policy items_read on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_staff() or exists(select 1 from public.delivery_jobs d where d.order_id=o.id and d.driver_id=auth.uid()))));
create policy delivery_read on public.delivery_jobs for select using(public.is_staff() or driver_id=auth.uid());create policy delivery_staff_write on public.delivery_jobs for all using(public.is_staff()) with check(public.is_staff());create policy delivery_driver_update on public.delivery_jobs for update using(driver_id=auth.uid()) with check(driver_id=auth.uid());
create policy settings_read on public.app_settings for select using(true);create policy settings_write on public.app_settings for all using(public.is_staff()) with check(public.is_staff());

insert into public.categories(name,slug,emoji,sort_order) values('Ron','ron','🥃',1),('Whisky','whisky','🥃',2),('Vino','vino','🍷',3),('Cerveza','cerveza','🍺',4),('Tequila','tequila','🌵',5),('Vodka','vodka','🍸',6),('Espumantes','espumantes','🥂',7),('Mixers y Snacks','mixers-snacks','🧊',8);
insert into public.app_settings(key,value) values('store',jsonb_build_object('name','CELICOR La Castellana','address','Av. Blandín con Calle Mata de Coco, La Castellana, Caracas','whatsapp','584242583500','phone','+582122634948','currency','USD')),('delivery',jsonb_build_object('fee',3,'pickup_enabled',true,'delivery_enabled',true));
insert into public.products(category_id,brand,name,slug,description,size,price,box_qty,box_price,stock,featured) select id,'Santa Teresa','Superior 1 Litro','santa-teresa-superior-1l','Licor de ron seco, perfecto para disfrutar puro o mezclado.','1 L',4.50,12,51,24,true from public.categories where slug='ron';
insert into public.products(category_id,brand,name,slug,description,size,price,box_qty,box_price,stock,featured) select id,'Santa Teresa','Carta Roja 1 Litro','santa-teresa-carta-roja-1l','Licor de ron seco de color rojizo con aroma a madera.','1 L',5.50,12,60,24,false from public.categories where slug='ron';
insert into public.products(category_id,brand,name,slug,description,size,price,box_qty,box_price,stock,featured) select id,'Santa Teresa','Gran Reserva','santa-teresa-gran-reserva-075','Ron envejecido hasta 5 años en barricas de roble.','0,75 L',9.00,6,50,18,true from public.categories where slug='ron';
insert into public.products(category_id,brand,name,slug,description,size,price,box_qty,box_price,stock,featured) select id,'Santa Teresa','Linaje','santa-teresa-linaje','Ron premium de mezclas de rones añejos de primera calidad.','0,70 L',14.95,6,82,12,true from public.categories where slug='ron';
insert into public.products(category_id,brand,name,slug,description,size,price,box_qty,box_price,stock,featured) select id,'Santa Teresa','Solera 1796','santa-teresa-1796','Ron súper premium envejecido mediante el proceso Solera.','0,75 L',26.90,6,152,12,true from public.categories where slug='ron';
insert into public.products(category_id,brand,name,slug,description,size,price,box_qty,box_price,stock,featured) select id,'Carúpano','Carúpano Extra','carupano-extra-1l','Licor seco elaborado con ron envejecido en roble blanco americano.','1 L',6.00,12,65,24,false from public.categories where slug='ron';
insert into public.products(category_id,brand,name,slug,description,size,price,box_qty,box_price,stock,featured) select id,'Carúpano','Añejo 6 Años','carupano-anejo-6','Ron con añejamiento cerrado en barricas de roble blanco americano.','0,75 L',12.50,12,144,18,true from public.categories where slug='ron';
insert into public.products(category_id,brand,name,slug,description,size,price,box_qty,box_price,stock,featured) select id,'Carúpano','Oro 12 Años','carupano-oro-12','Ron con añejamiento cerrado y madres de reservas especiales.','0,75 L',18.90,12,216,12,true from public.categories where slug='ron';
